name: Conventional Changelog action

on:
  push:
    branches:
      - ci
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  changelog:
  name: Create changelog
  runs-on: ubuntu-latest
  steps:
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}