name: Conventional Changelog action

on:
  push:
    branches:
      - ci
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Generate changelog
        id: changelog
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKE }}
          create-summary: true

      - name: Create Release
        uses: actions/create-release@v1
        if: steps.changelog.outputs.skipped != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKE }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}