name: CI

on:
  push: [ ci ]

jobs:
  # Tests dev-only scripts across all supported dev environments
  test-dev:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - run: echo "${{ github.actor }}"
      - uses: actions/checkout@v3
        with:
          # fetch all tags which are required for `yarn release:changelog`
          fetch-depth: 0
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - run: npm install
        env:
          # Don't need playwright in this job
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npm run release:build
      - run: npm run release:changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: npm run release:tag
        run: |
          git remote -v
          npm run release:tag --dryRun