name: Generate changelog on every conventional commit 
on: push

jobs:
 test:
   runs-on: [ ubuntu-latest ]
   strategy:
     matrix:
       node-version: [16.x] 
   steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
     - run: npm install
     - name: Install changelog
       run: npm i generate-changelog
     - name: Generate changelog
       run: npm run changelog

