name: Generate changelog on every conventional commit 
on:
  push:
    branches:
      - xx

jobs:
 generate changelog:
   runs-on: [ ubuntu-latest ]
   strategy:
     matrix:
       node-version: [16.x]
   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci
    # or one-off:
    - run: npm i generate-changelog
    - uses: actions/github-script@v6
      with:
        script: |
          npm run changelog


