name: Release

on:
  push:
    branches: [ci]

jobs:
  release:
    name: Github release
    runs-on: ubuntu-latest
    steps:
      - name: version
        run: echo "::set-output name=version::$(./bin/aws-deploy-template --version)"
        id: version
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ver-${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




      