name: Release

on:
  push:
    branches: [ main ]

jobs:
  prepare:
    name: Preparing build context
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.semver.outputs.semantic_version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Semver run
        id: semver
        uses: lukaszraczylo/semver-generator@v1
        # you can also use v1 tag which _should_ automatically upgrade to latest
        # uses: lukaszraczylo/semver-generator@v1
        with:
          config_file: config.yaml
          # either...
          repository_local: true
          # or...
          repository_url: https://github.com/SawaGawlau/aws-deploy-template
          # when using remote repository, especially with private one:
          github_username: sawa
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Semver check
        run: |
          echo "Semantic version detected: ${{ steps.semver.outputs.semantic_version }}"